### ISSUE TITLE
关于硬件清单的疑问

### ISSUE THREAD

**Issue by nobody284** [Mingrui-Yu/RaspberryCar#3]
你好.看到树梅派智能小车这个项目,很感兴趣
关于硬件清单我有些疑问,特来请教

我已经有树梅派2的硬件和独立的WIFI网卡
在淘宝店铺只需要购买小车套件就可以实现本项目的所有功能了是吧?
我有两点疑问:
1 看到你的硬件清单里提到CSI接口的摄像头,但是淘宝店铺只提供了USB接口的摄像头 这个没问题吧?
2 默认套餐里的电池续航如何,是否有必要购买高规格的电池?

**Comment by Mingrui-Yu** [comment]
不好意思回复迟了

应该是的，不过我对树莓派2的特性不太了解，应该问题不大吧

USB摄像头的程序调用方式和CSI不太一样，具体我在README中也给了参考资料了，写代码的时候需要修改一下，其他应该是没有问题的。

套件里的电池续航很差，建议在淘宝买稍微好一点的吧，然后两组电池轮着用。

**Comment by nobody284** [comment]
多谢回答 过两天小车到货就可以开始动手实践了
